displayName=Booms Epic Sounds
author=TheArkane
description=Custom sound notifications for loot, PvP, deaths, prayer and achievements.
tags=sounds,loot,pvm,pvp
plugins=com.thearkane.boomsepicsounds.BoomsEpicSoundsPlugin